### ISSUE TITLE
Cannot watch video by ./render in macOS

### ISSUE THREAD

**Issue by znnby1997** [geek-ai/MAgent#67] opened 2019-12-19 16:34 UTC
`$ ./render
[2019-12-20 00:26:05] [0x1080ad5c0] Listening on port 9030
[2019-12-20 00:26:15] [0x1080ad5c0] successfully connected to the client
[2019-12-20 00:26:17] [0x1080ad5c0] message receive: lconfig.json,video_1.txt
[2019-12-20 00:26:17] [0x1080ad5c0] magent::render::RenderException: "invalid handle of the map data file"
[2019-12-20 00:26:24] [0x1080ad5c0] the client closed the connection
^C
(base) `
clicking the index.html file will lead to the RenderException: "invalid handle of the map data file"

**Comment by Kipsora** [comment] 2019-12-19 16:38
Please refer to these existing issues #65 #48 #21. If you cannot solve it, please show how you execute the render (i.e. working path) and your files under the directory ``./build/render''. The error is caused by the render not being able to find the video data file.

**Comment by znnby1997** [comment] 2019-12-19 16:44
`MAgent/build/render on git:master x [0:42:15] 
$ ls
config.json index.html  js          render      static.map  vendor
(base) 
`
I find there is no video_1.txt in /build/render/

**Comment by Kipsora** [comment] 2019-12-19 16:46
Could you please provide your building messages and the files in `/build/render` as well? We need these information to pinpoint the problem.

**Comment by znnby1997** [comment] 2019-12-19 16:52
<img width="490" alt="屏幕快照 2019-12-20 上午12 50 58" src="https://user-images.githubusercontent.com/36070860/71192233-d4f44700-22c2-11ea-9878-ca771c62f9d4.png">
<img width="317" alt="屏幕快照 2019-12-20 上午12 52 31" src="https://user-images.githubusercontent.com/36070860/71192331-066d1280-22c3-11ea-8a39-64fa7365369a.png">

**Comment by Kipsora** [comment] 2019-12-19 17:15
You need to first run the scripts to generate the video file and then are able to watch it. Please follow the README to execute any of the training scripts (i.e. battle/gathering/pursuit)

**Comment by znnby1997** [comment] 2019-12-19 17:18
only executing demo_api.py couldn't generate the video file? I execute the demo_api.py.

**Comment by Kipsora** [comment] 2019-12-19 17:21
No. `api_demo.py` is only showing examples on how to use our APIs. Please follow the [README](https://github.com/geek-ai/MAgent/blob/master/README.md) to use our codes.

**Comment by Kipsora** [comment] 2019-12-19 17:26
Issue closed since duplicate of #48. If you still have problems, please reopen the issue.

**Closed by Kipsora** 2019-12-19 17:26 UTC
